import {StyleSheet} from 'react-native';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';
const localStyles = StyleSheet.create({
  flex1: {flex: 1},
  inputContainerStyle: {
    height: 50,
    justifyContent: 'flex-end',
    alignSelf: 'center',
    marginVertical: 0,
    borderWidth: 1,
    // borderColor: '#0000001A',
    borderRadius: 10,
    // shadowColor: '#00000029',
    shadowOffset: {width: 1, height: 5},
    // elevation: 6,
    // backgroundColor: '#0000001A',
    marginHorizontal: -8,
  },
  inputTextStyle: {
    marginHorizontal: 5,
    fontSize: 14,
    color: '#777171',
  },
  termsView: {
    flexDirection: 'row',
    // marginBottom: 10,
    alignSelf: 'center',
    // paddingTop: hp('2%'),
    paddingHorizontal: wp('1%'),
    alignItems: 'center',
  },
  unCheckBox: {
    borderWidth: 1,
    height: 18,
    width: 18,
    borderColor: '#4B79D8',
  },
  inputExperienceContainerStyle: {
    height: 50,
    width: 70,
    borderWidth: 1,
    borderColor: '#E6E6E6',
    borderRadius: 10,
    shadowColor: '#00000029',
    backgroundColor: '#E6E6E6',
    elevation: 6,
  },
  editPicTouchable: {
    justifyContent: 'center',
    width: '100%',
    borderWidth: 1,
    borderRadius: 5,
    borderColor: '#4B79D8',
    padding: 10,
  },
  editPicText: {
    fontWeight: '500',
    color: '#4B79D8',
  },
  image: {
    height: 100,
    width: 100,
    borderRadius: 50,
    marginVertical: 20,
  },
  inputHealthContainerStyle: {
    height: 45,
    width: 60,
    borderWidth: 1,
    borderColor: '#4B79D8',
    borderRadius: 10,
  },
  unCheckBoxAddress: {
    borderWidth: 1,
    height: 15,
    width: 15,
    borderColor: '#4B79D8',
  },
  personalHeaderMainContainer: {
    // height: 280,
    backgroundColor: '#4B79D8',
    width: '100%',
  },
  menuTigerView: {
    // marginTop: 5,
    padding: 5,
    paddingVertical: 0,
    justifyContent: 'center',
    alignItems: 'center',
  },
  imageCircleView: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 20,
  },
  centerCircle: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  circlePosition: {
    position: 'absolute',
  },
  innerImageView: {
    width: 80,
    height: 80,
    borderRadius: 40,
    marginTop: 10,
    alignItems: 'center',
  },
  cameraPosition: {
    right: -1,
    bottom: 1,
    position: 'absolute',
  },
  cameraOptionsView: {
    padding: 0,
    margin: 10,
  },
  optionsView: {padding: 0},
  personalHeaderTextContainer: {
    justifyContent: 'center',
    // alignItems: 'center',
    marginTop: 10,
  },
  starsView: {flexDirection: 'row', padding: 10},
  btnView: {
    alignItems: 'flex-end',
    elevation: 8,
    top: -15,
    right: 15,
  },
  personalInputContainer: {backgroundColor: '#00000000'},
  innerContainerMargin: {margin: 10},
  backgroundFlowerContainer: {alignItems: 'flex-end'},
  backgroundFlowerPositions: {position: 'absolute', zIndex: -9},
  labelTextStyles: {margin: 5, color: '#9F9F9F', fontSize: 14},
  lastUpdateText: {color: '#fff', fontSize: 14},
  userNameText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
    // textAlign: 'center',
  },
  userWorkingText: {color: '#fff', fontSize: 16},
});

export default localStyles;
