let English = {
  today: 'Today',
  loadingDataPleaseWait: 'Loading Data Please wait',
  somethingWentWrong: 'Something went Wrong',
  noDataAvailable: 'No Data Available',
  retry: 'Retry',
  speak: 'SPEAK',
  write: 'WRITE',
  read: 'READ',
  mobile: 'Mobile',
  lastName: 'Last Name',
  lastUpdated: 'Last Updated',
  takeFromCamera: 'TAKE FROM CAMERA',
  selectFromPhone: 'Gallery',
  myPost: 'My Post',
  published: 'PUBLISHED',
  postApprovalPending:
    'Your Post is pending for approval by admin. You will be notified once it is published.',
  title: 'Title',
  description: 'Description',
  video: 'Video',
  photo: 'Photo',
  invalidInput: 'Invalid Input',
  home: 'HOME',
  myProfile: 'MY PROFILE',
  qrScanner: 'QR SCANNER',
  sahyog: 'SAHYOG',
  callFromPhone: 'Call from Phone', // Remove This
  logout: 'LOG OUT',
  samajhdar: 'Samajhdar',
  shiksha: 'Shiksha',
  rojgar: 'Rojgar',
  parivar: 'Parivar',
  samachar: 'Samachar',
  politics: 'POLITICS',
  entertainment: 'ENTERTAINMENT',
  sports: 'SPORTS',
  health: 'HEALTH',
  profileSummary: 'Profile Summary',
  healthDetail: 'Health Detail',
  fullName: 'Full Name',
  firstName: 'First Name',
  middleName: 'Middle Name',
  address: 'ADDRESS',
  currentAddress: 'CURRENT ADDRESS',
  pincode: 'PINCODE',
  city: 'CITY/TOWN/VILLAGE',
  state: 'STATE',
  permanentAddress: 'PERMANENT ADDRESS',
  permanentAddressSameAsAbove: 'PERMANENT ADDRESS SAME AS ABOVE ADDRESS',
  professional: 'PROFESSIONAL',
  industry: 'INDUSTRY',
  trade: 'TRADE',
  experience: 'EXPERIENCE',
  skills: 'SKILLS',
  industrySkills: 'INDUSTRY SKILLS',
  computerSkills: 'COMPUTER SKILLS',
  personalDetails: 'PERSONAL DETAILS',
  gender: 'GENDER',
  dob: 'DATE OF BIRTH',
  healthMedical: 'HEALTH/MEDICAL',
  height: 'HEIGHT',
  weight: 'WEIGHT',
  bloodGroup: 'BLOOD GROUP',
  education: 'EDUCATION',
  language: 'LANGUAGE',
  hindi: 'HINDI',
  english: 'ENGLISH',
  marathi: 'MARATHI',
  personalIDAccounts: 'PERSONAL ID/ ACCOUNTS',
  documentType: 'DOCUMENT TYPE',
  documentNumber: 'DOCUMENT NUMBER',
  resume: 'RESUME',
  workProfile: 'Work Profile',
  verify: 'Verify',
  all: 'ALL',
  saved: 'Saved',
  applied: 'Applied',
  offered: 'Offered',
  closed: 'Closed',
  rejectedByEmployer: 'Rejected by employer',
  rejectedByCandidate: 'Rejected by candidate',
  offerAccepted: 'Offer accepted',
  shortListed: 'Shortlisted',
  search: 'Search',
  close: 'Close',
  invalidAccountNumber: 'Invalid Account number',
  mandatoryField: 'This field is Mandatory',
  invalidIFSCCode: 'Invalid IFSC code',
  invalidGSTINNumber: 'Invalid GSTIN number',
  gstinNumberError: 'GSTIN number should 15 character long',
  invalidPan: 'Invalid PAN number',
  invalidAadharNumber: 'Invalid Aadhar number',
  invalidPassportNumber: 'Invalid Passport Number',
  invalidLicenseNumber: 'Invalid Driving License Number',
  invalidField: 'This field is Mandatory',
  invalidEmail: 'Invalid Email',
  invalidPassword: 'Invalid Password',
  passwordLengthError: 'Passoword should be atleast 6 digit long',
  invalidNumber: 'Number is invalid',
  invalidSpace: 'Invalid Space',
  invalidCharacters: 'Invalid Characters',
  invalidEmployeeCode: 'Invalid Employee Code',
  employeeCodeLength: 'Employee Code should be of 6 digit',
  mobileNumberLengthError: 'Mobile Number should be of 10 digit',
  invalid: 'Invalid',
  invalidDescription: 'Invalid Description',
  invalidCompanyName: 'Invalid Company Name',
  invalidCompanyLocation: 'Invalid Company Location',
  invalidName: 'Invalid Name',
  invalidRelation: 'Invalid Relation',
  successfully: 'Successfully',
  profileUpdateSuccess: 'Profile Updated Successfully',
  photoAddSuccess: 'Photo Added Successfully',
  photoDeatilAddedSuccess: 'Your Photo Detail Added Save Successfully',
  videoAddSuccess: 'Your Video Added Successfully',
  jobApplySuccess: 'Job Applied Successfully',
  shramNeedsYourPermissions: 'Shram needs your certain permissions',
  askMeLater: 'Ask Me Later',
  cancel: 'Cancel',
  ok: 'OK',
  downloadedSuccessAt: 'Downloaded Successfully at',
  fileAccessPermissionRequired: 'File access permission denied',
  tradeSkill: 'Trade skill',
  computer: 'Computer',
  profile: 'Profile',
  uploadPhotos: 'Uploaded Photos',
  create: 'Create',
  add: 'Add',
  delete: 'Delete',
  upload: 'Upload',
  recordVideoOrPhoto: 'Please Record Video / Click Photo',
  addVideoResume: 'Kindly Add Video to Your Resume',
  pendingApproval: 'PENDING APPROVAL',
  rejected: 'REJECTED',
  connection: 'CONNECTION',
  messages: 'MESSAGES',
  contacts: 'CONTACTS',
  noContactsFound: 'NO CONTACTS FOUND',
  pleaseSync: 'PLEASE SYNC YOUR PHONE BOOK',
  sync: 'SYNC',
  searchContactsHere: 'SEARCH CONTACTS HERE',
  bookmark: 'BOOKMARK',
  company: 'Company',
  location: 'Location',
  workReference: 'Work Reference',
  done: 'Done',
  friendRequestAccepeted: 'Friend Request Requested',
  friendRequestSent: 'Friend Request Sent',
  friendRequest: 'Friend Request',
  friendRequestRejected: 'Rejected',
  friendRequestAccepted: 'Accepted',
  post: 'POST',
  addNew: 'Add new',
  from: 'From',
  to: 'To',
  reference: 'Reference',
  workRelationship: 'Work Relationship',
  assessment: 'Assessment',
  submit: 'Submit',
  takePhotoVideo: 'Please take Photo/Video',
  titleRequired: 'Title is Required',
  imageSizeLimit: 'Image cannot be greater than 5 mb',
  videoTimeLimit: 'Video cannot be greater than 40 sec',
  videoSizeLimit: 'Video cannot be greater than 50 mb',
  fetchQRFailed: 'Could not fetch QR code',
  pincodeRequired: 'Pincode Required',
  cityRequired: 'City Required',
  stateRequired: 'State Required',
  permanentPincodeRequired: 'Permanent Pincode Required',
  permanentCityRequired: 'Permanent City Required',
  permanentStateRequired: 'Permanent State Required',
  documentNameRequired: 'Document Number is Required',
  documentTypeRequired: 'Document Type is Required',
  documentPhotoRequired: 'Document Photo is Required',
  addDOB: 'Please Add Date of Birth',
  weightNotMoreThan: 'Weight should not more than 200',
  inchNotMoreThan: 'Inch should not more than 12',
  fullNameRequired: 'Full Name Required',
  firstNameRequired: 'First Name Required',
  lastNameRequired: 'Last Name Required',
  selectIndustry: 'Please select atleast 1 industry',
  selectTrade: 'Please select trade',
  skillRequired: 'Please select atleast 1 skill',
  selectAtleastOneAnswer: 'Please select atleast one answer',
  selectCheckBox: 'Kindly select the checkbox',
  otpSent: 'OTP Sent Successfully',
  requestOtpFirst: 'Please request for OTP first',
  somethingWentWrongTry: 'Something went wrong. Try again later',
  startRecognition: 'Press mic to start recognition',
  results: 'Results',
  changeLanguage: 'Change Language',
  version: 'Version',
  scanQrCode: 'Scan a qr code',
  back: 'Back',
  noNotifications: 'No Notifications',
  yesterday: 'Yesterday',
  createNew: 'Create New',
  createNewPost: 'Create New Post',
  addWorkProfile: 'Please Add Your Work Profile',
  register: 'Register',
  videoResume: 'VIDEO RESUME',
  shiftTiming: 'Shift Timing',
  jobType: 'Job Type',
  postedOn: 'Posted On',
  pastNotification: 'Past Notification',
  noDataFound: 'No data found',
  jobFilter: 'Job Filter',
  noPhotosFound: 'No photos found, kindly add atleast one photo',
  noResumeFound: 'Kindly Add Media For Your Resume',
  noDataAfterRedirect: 'Data you are looking for is not available on this page',
};
export default English;
