let Hinglish = {
  today: 'Aaj',
  loadingDataPleaseWait: 'Loading Data',
  somethingWentWrong: '😥 Something went Wrong',
  noDataAvailable: '😥 Data Unavailable',
  retry: '😥 Retry ',
  speak: 'Bolna',
  write: 'Likhna',
  read: 'Padhna',
  mobile: 'Mobile',
  lastName: 'Surname',
  lastUpdated: 'Pichala Update',
  takeFromCamera: 'Camera 📷',
  selectFromPhone: 'Gallery',
  myPost: 'Mere Posts',
  published: 'PUBLISHED',
  // published: '✔️',
  postApprovalPending: 'Naya Post Approval Mein Hai',
  title: 'Title',
  description: 'Aur Batao',
  video: 'Video',
  photo: 'Photo',
  invalidInput: '❌ Entry',
  home: 'HOME',
  myProfile: 'Mera Profile',
  qrScanner: 'Scan QR Code',
  sahyog: 'SAHYOG',
  callFromPhone: 'Call from Phone', // Remove This
  logout: 'LOG OUT',
  samajhdar: 'Samajhdar',
  shiksha: 'Shiksha',
  rojgar: 'Rojgar',
  parivar: 'Parivar',
  samachar: 'Samachar',
  politics: 'POLITICS',
  entertainment: 'ENTERTAINMENT',
  sports: 'SPORTS',
  health: 'HEALTH',
  healthDetail: 'Health Detail',
  profileSummary: 'Aapka Bio-Data',
  fullName: 'Aapka Pura Naam',
  firstName: 'Aapka Naam',
  middleName: 'Pitaji/Mataji ka Naam',
  address: 'ADDRESS',
  currentAddress: 'Abhi ka Address',
  pincode: 'PINCODE',
  city: 'CITY/TOWN/VILLAGE',
  state: 'STATE',
  permanentAddress: 'PERMANENT ADDRESS',
  permanentAddressSameAsAbove: 'Permanent Address Bhi Same Hai',
  professional: 'PROFESSIONAL',
  industry: 'INDUSTRY',
  trade: 'Kaam',
  experience: 'EXPERIENCE',
  skills: 'SKILLS',
  industrySkills: 'INDUSTRY SKILLS',
  computerSkills: 'COMPUTER SKILLS',
  personalDetails: 'PERSONAL DETAILS',
  gender: 'GENDER',
  dob: 'DATE OF BIRTH',
  healthMedical: 'HEALTH/MEDICAL',
  height: 'HEIGHT',
  weight: 'WEIGHT',
  bloodGroup: 'BLOOD GROUP',
  education: 'EDUCATION',
  language: 'LANGUAGE',
  hindi: 'HINDI',
  english: 'ENGLISH',
  marathi: 'MARATHI',
  personalIDAccounts: 'PERSONAL ID/ ACCOUNTS',
  documentType: 'DOCUMENT TYPE',
  documentNumber: 'DOCUMENT NUMBER',
  resume: 'RESUME',
  workProfile: 'Work Profile',
  verify: 'Verify',
  all: 'ALL',
  saved: 'Saved Jobs',
  applied: 'Applied Jobs',
  offered: 'Job Offer',
  closed: 'Job Closed',
  rejectedByEmployer: 'Not selected',
  rejectedByCandidate: 'Aapke Dwara Rejected',
  offerAccepted: 'Congrats Aap Select Hogaye Ho 👏🏻',
  shortListed: 'Aapke Shortlisted',
  search: '🔍',
  close: 'Close',
  invalidAccountNumber: '❗ Account number',
  mandatoryField: 'Ye Bharna Zarrori Hai ❗',
  invalidIFSCCode: 'Invalid IFSC code',
  invalidGSTINNumber: 'Invalid GSTIN number',
  gstinNumberError: 'GSTIN number should 15 character long',
  invalidPan: '❌ PAN number',
  invalidAadharNumber: '❌ Aadhar number',
  invalidPassportNumber: '❌ Passport Number',
  invalidLicenseNumber: '❌ Driving Number',
  invalidEmail: 'Invalid Email',
  invalidPassword: 'Invalid Password',
  passwordLengthError: 'Passoword should be atleast 6 digit long',
  invalidNumber: 'Number is invalid',
  invalidSpace: 'Invalid Space',
  invalidCharacters: 'Invalid Characters',
  invalidEmployeeCode: 'Invalid Employee Code',
  employeeCodeLength: 'Employee Code should be of 6 digit',
  mobileNumberLengthError: 'Mobile Number should be of 10 digit',
  invalid: 'Invalid ❗',
  invalidDescription: 'Invalid Description ❗',
  invalidCompanyName: 'Invalid Company Name ❗',
  invalidCompanyLocation: 'Invalid Company Location ❗',
  invalidName: 'Invalid Name ❗',
  invalidRelation: 'Invalid Relation ❗',
  successfully: '✔️ Successfully',
  profileUpdateSuccess: 'Profile Updated ✔️',
  photoAddSuccess: 'Photo Added ✔️',
  photoDeatilAddedSuccess: 'Photo Detail Saved ✔️',
  videoAddSuccess: 'Video Added ✔️',
  jobApplySuccess: 'Applied ✔️',
  shramNeedsYourPermissions: 'Shram Aapse Kuch Permissions Maangta Hai',
  askMeLater: 'Ask Me Later',
  cancel: 'Cancel',
  ok: 'OK',
  downloadedSuccessAt: 'Downloaded Successfully at',
  fileAccessPermissionRequired: 'File access permission denied',
  tradeSkill: 'Skill',
  computer: 'Computer',
  profile: 'Profile',
  uploadPhotos: 'Uploaded Photos',
  create: 'Create',
  add: 'Add',
  delete: 'Delete',
  upload: 'Upload',
  recordVideoOrPhoto: 'Please Video Record Karo/Photo Kheecho',
  addVideoResume: 'Video Resume Mein Add Karo',
  pendingApproval: 'PENDING APPROVAL',
  rejected: 'REJECTED',
  // rejected: 'Reject Kar Diya ❌',
  connection: 'CONNECTION',
  messages: 'MESSAGES',
  contacts: 'CONTACTS',
  noContactsFound: 'Contacts Nahi Mile',
  pleaseSync: 'Phone Book Add Karo',
  sync: 'SYNC',
  searchContactsHere: 'CONTACTS',
  bookmark: 'BOOKMARK',
  company: 'Company',
  location: 'Location',
  workReference: 'Work Reference',
  done: 'Done',
  friendRequestAccepeted: 'Request Sweekar Kar Diya',
  friendRequestSent: 'Request Bhej Diya ✔️',
  friendRequest: 'Friend Request',
  friendRequestRejected: 'Reject Kar Diya',
  friendRequestAccepted: 'Accept Kar Diya',
  post: 'POST',
  addNew: 'Add new',
  from: 'From',
  to: 'To',
  reference: 'Kisne Refer Kia',
  workRelationship: 'Work Relationship',
  assessment: 'Aapka Test',
  submit: 'Done',
  takePhotoVideo: 'Photo/Video lijiye',
  titleRequired: 'Title Zarrori Hai ❗',
  imageSizeLimit: 'Photo Size 5MB Tak',
  videoTimeLimit: 'Video 40 Secs Tak',
  videoSizeLimit: 'Video 50MB Tak',
  fetchQRFailed: '❌ QR Code Invalid hai',
  pincodeRequired: 'Pincode Zarrori Hai ❗',
  cityRequired: 'City Zarrori Hai ❗',
  stateRequired: 'State Zarrori Hai ❗',
  permanentPincodeRequired: 'Permanent Pincode Zarrori Hai ❗',
  permanentCityRequired: 'Permanent City Zarrori Hai ❗',
  permanentStateRequired: 'Permanent State Zarrori Hai ❗',
  documentNameRequired: 'Document Number Zarrori Hai ❗',
  documentTypeRequired: 'Document Type Zarrori Hai ❗',
  documentPhotoRequired: 'Document Photo Zarrori Hai ❗',
  addDOB: 'Birth Date Dijiye',
  weightNotMoreThan: '200 Kgs tak',
  inchNotMoreThan: '12 Inch takk',
  fullNameRequired: 'Full Name Zarrori Hai',
  firstNameRequired: 'First Name Zarrori Hai',
  lastNameRequired: 'Last Name Zarrori Hai',
  selectIndustry: 'Industry Check Karo',
  selectTrade: 'Kaam Check Karo',
  skillRequired: 'Skill Zarrori Hai',
  selectAtleastOneAnswer: 'Select One',
  selectCheckBox: 'Select Checkbox',
  otpSent: 'OTP Bhej Diya Hai ✔️',
  requestOtpFirst: 'Request OTP',
  somethingWentWrongTry: '😥 Try Again',
  startRecognition: 'Press Mic',
  results: 'Results',
  changeLanguage: 'Change Language',
  version: 'Version',
  scanQrCode: 'Scan QR',
  back: 'Back',
  noNotifications: 'Koi Notifications Nahi Hai :(',
  yesterday: 'Yesterday',
  createNew: 'Naya Banaye',
  createNewPost: 'Naya Post Banaye',
  addWorkProfile: 'Aapki Last Naukri Add karein',
  register: 'Register',
  videoResume: 'VIDEO RESUME',
  shiftTiming: 'Shift Ka Samay',
  jobType: 'Job Type',
  postedOn: 'Post Date',
  pastNotification: 'Pichle Notifications',
  noDataFound: 'Data Nahi Mila',
  jobFilter: 'Job Filter',
  noPhotosFound: 'Koi Photo Nahi Mila, Photos Add Karein',
  noResumeFound: 'Kripya Resume ke liye Media Add Karien',
  noDataAfterRedirect: 'Data iss page par available nahi hai',
};
export default Hinglish;
